# Generated by Django 4.1.7 on 2023-03-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Releasedate', models.DateField()),
                ('Moviename', models.CharField(max_length=30)),
                ('Actor', models.CharField(max_length=30)),
                ('Actress', models.CharField(max_length=30)),
                ('Director', models.CharField(max_length=30)),
                ('Rating', models.FloatField()),
            ],
        ),
    ]
